# Configuration file for the project
# Root directory for storing data
artifacts_root: artifacts

# Configuration for data ingestion
data_ingestion:
  # Root directory for data ingestion
  root_dir: artifacts/data_ingestion
  # URL to download the data from
  source_URL: https://github.com/Adeliyio/Fake_News_Detection/raw/main/winequality-data.zip
  # Local file path where the downloaded data will be stored
  local_data_file: artifacts/data_ingestion/data.zip
  # Directory where the downloaded data will be extracted
  unzip_dir: artifacts/data_ingestion


  # Configuration for data validation
data_validation:
  # Root directory for data validation
  root_dir: artifacts/data_validation

  # Directory where the data will be extracted
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv

  # File path for storing status information
  STATUS_FILE: artifacts/data_validation/status.txt


  # Configuration for data transformation
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

 # Configuration for model trainer
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

